### ISSUE TITLE
about 'cars3d.npz' file

### ISSUE THREAD

**Issue by ChengJiacheng** [avivga/lord#1]
Hi,

I noticed that a 'cars3d.npz' file is needed for training on cars3d dataset.
I am wondering if this file is publically available? Any information would be appreciated, thanks!

**Comment by avivga** [comment]
Thanks for your interest.

We follow disentanglement_lib in downloading and extracting the cars3d dataset.

Download: https://github.com/google-research/disentanglement_lib/blob/master/bin/dlib_download_data
Extract: https://github.com/google-research/disentanglement_lib/blob/master/disentanglement_lib/data/ground_truth/cars3d.py
(_load_data gives you the numpy array you need to create cars3d.npz)

Good luck!
