### ISSUE TITLE
About Over LORD

### ISSUE THREAD

**Issue by baopmessi** [avivga/lord#2]
Thank for awesome your work !!
When do you plan to public code of Over Lord ? 
I'm looking forward to it ! Hope soon!
I confuse that why content code with an additive Gaussian noise ensures that no
content information is present in the class representation. I think content code still can contain class information 
when training in later iterations . Hope you can explain clearly.

**Comment by avivga** [comment]
Thanks for your interest in our work.
We plan to release OverLORD as soon as possible, hopefully by the end of this month.

Regarding the regularization, the role of penalizing the content code is the opposite i.e. preventing class information from leaking into the content representation. The intuition is that the noise and the activation decay penalty reduces the channel capacity (see [Shannon Hartley theorem](https://en.wikipedia.org/wiki/Shannon%E2%80%93Hartley_theorem)) and therefore the most efficient embedding would encode mainly the content information as the class can be inferred from the complementary representation to generate the image.

**Comment by baopmessi** [comment]
Thanks you so much!
If for each class has only 1 sample ( 1 image for each identity), whether it has an adverse effect on the ability to learn class semantics into vector y and uncorrelate attributes ( pose) into vector u . I mean it can be entangled or swapped because the role of these 2 vectors during training is the same (both are embedding to generate image). (sorry for my english)

**Comment by avivga** [comment]
Exactly. More specifically, if there is only a single sample in each class, I guess the class embedding would encode all the information as it is not regularized, in contrast to the content. This setting sounds like "unsupervised disentanglement" which is known to be impossible without any inductive bias. If this is your case, you might opt for designing a biased architecture according to your task (e.g. "Swapping Autoencoder for Deep Image Manipulation").

**Comment by baopmessi** [comment]
Thanks you!
I look forward to OverLORD as well as hope you will release pytorch code.
